name: Deploy CDK Stack

on:
  push:
    branches:
      - main
  workflow_dispatch: # Add this line to enable manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Bootstrap CDK environment
        run: cdk bootstrap aws://527571104735/us-east-1

      - name: Synthesize CDK Stacks
        run: cdk synth

      - name: Deploy CDK stack
        run: cdk deploy --region us-east-1 --require-approval never
